server:
  port: 8080
spring:
  mvc:
    servlet:
      load-on-startup: 1
  datasource:
    username: root
    password: zyf20020523.
    url: jdbc:mysql://127.0.0.1:3306/score_management?serverTimezone=UTC
  redis:
    port: 6379

logging:
  level:
    com.nb: debug
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)


